### Create User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email":"2a@ftsss.com",
  "password":"manhaa",
  "admin":true
}

### Create User
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email":"2a@ftsss.com",
  "password":"manhaa",
}


### finUserBy ID
GET http://localhost:3000/auth/7

### Search User by
GET  http://localhost:3000/auth?email=1

### remove record
DELETE  http://localhost:3000/auth/6

### Update userr
PATCH http://localhost:3000/auth/6
Content-Type: application/json

{
  "email":"a@fsoft.cmmm",
}